name: Build Unsigned IPA
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build App
        run: |
              xcodebuild -project ComicFlow.xcodeproj -list
            
              xcodebuild -project ComicFlow.xcodeproj -target ComicFlow -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CONFIGURATION_BUILD_DIR="$(pwd)/build" build
            
              mkdir -p Payload
              cp -r build/*.app Payload/
              zip -r ComicFlow.ipa Payload
              

      - name: Upload IPA
        uses: actions/upload-artifact@v7
        with:
          name: Unsigned-App
          path: App.ipa
